/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
